#############################################################################
# Makefile for building: goodby
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  goodby.pro
# Template: app
# Command: /usr/local/lib/qt5/bin/qmake -o Makefile goodby.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIC $(DEFINES)
INCPATH       = -I. -I../../../local/include/qt5 -I../../../local/include/qt5/QtGui -I../../../local/include/qt5/QtCore -I. -I../../../local/include -I../../../local/include -I../../../local/lib/qt5/mkspecs/freebsd-clang
QMAKE         = /usr/local/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = goodby1.0.0
DISTDIR = /usr/home/gbc/Cstuff/.tmp/goodby1.0.0
LINK          = clang++
LFLAGS        = -pthread -Wl,-rpath,/usr/local/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -lQt5Gui -lQt5Core -lGL 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = hello.c 
OBJECTS       = hello.o
DIST          = ../../../local/lib/qt5/mkspecs/features/spec_pre.prf \
		../../../local/lib/qt5/mkspecs/common/unix.conf \
		../../../local/lib/qt5/mkspecs/common/freebsd.conf \
		../../../local/lib/qt5/mkspecs/common/sanitize.conf \
		../../../local/lib/qt5/mkspecs/common/gcc-base.conf \
		../../../local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../local/lib/qt5/mkspecs/common/clang.conf \
		../../../local/lib/qt5/mkspecs/qconfig.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_quick.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_webkit.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_declarative.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../local/lib/qt5/mkspecs/features/qt_functions.prf \
		../../../local/lib/qt5/mkspecs/features/qt_config.prf \
		../../../local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		../../../local/lib/qt5/mkspecs/features/spec_post.prf \
		../../../local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		../../../local/lib/qt5/mkspecs/features/default_pre.prf \
		../../../local/lib/qt5/mkspecs/features/resolve_config.prf \
		../../../local/lib/qt5/mkspecs/features/default_post.prf \
		../../../local/lib/qt5/mkspecs/features/warn_on.prf \
		../../../local/lib/qt5/mkspecs/features/qt.prf \
		../../../local/lib/qt5/mkspecs/features/resources.prf \
		../../../local/lib/qt5/mkspecs/features/moc.prf \
		../../../local/lib/qt5/mkspecs/features/unix/opengl.prf \
		../../../local/lib/qt5/mkspecs/features/unix/thread.prf \
		../../../local/lib/qt5/mkspecs/features/testcase_targets.prf \
		../../../local/lib/qt5/mkspecs/features/exceptions.prf \
		../../../local/lib/qt5/mkspecs/features/yacc.prf \
		../../../local/lib/qt5/mkspecs/features/lex.prf \
		goodby.pro  hello.c
QMAKE_TARGET  = goodby
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = goodby


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: goodby.pro ../../../local/lib/qt5/mkspecs/freebsd-clang/qmake.conf ../../../local/lib/qt5/mkspecs/features/spec_pre.prf \
		../../../local/lib/qt5/mkspecs/common/unix.conf \
		../../../local/lib/qt5/mkspecs/common/freebsd.conf \
		../../../local/lib/qt5/mkspecs/common/sanitize.conf \
		../../../local/lib/qt5/mkspecs/common/gcc-base.conf \
		../../../local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../local/lib/qt5/mkspecs/common/clang.conf \
		../../../local/lib/qt5/mkspecs/qconfig.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_quick.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_webkit.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_declarative.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../local/lib/qt5/mkspecs/features/qt_functions.prf \
		../../../local/lib/qt5/mkspecs/features/qt_config.prf \
		../../../local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		../../../local/lib/qt5/mkspecs/features/spec_post.prf \
		../../../local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		../../../local/lib/qt5/mkspecs/features/default_pre.prf \
		../../../local/lib/qt5/mkspecs/features/resolve_config.prf \
		../../../local/lib/qt5/mkspecs/features/default_post.prf \
		../../../local/lib/qt5/mkspecs/features/warn_on.prf \
		../../../local/lib/qt5/mkspecs/features/qt.prf \
		../../../local/lib/qt5/mkspecs/features/resources.prf \
		../../../local/lib/qt5/mkspecs/features/moc.prf \
		../../../local/lib/qt5/mkspecs/features/unix/opengl.prf \
		../../../local/lib/qt5/mkspecs/features/unix/thread.prf \
		../../../local/lib/qt5/mkspecs/features/testcase_targets.prf \
		../../../local/lib/qt5/mkspecs/features/exceptions.prf \
		../../../local/lib/qt5/mkspecs/features/yacc.prf \
		../../../local/lib/qt5/mkspecs/features/lex.prf \
		goodby.pro \
		/usr/local/lib/libQt5Gui.prl \
		/usr/local/lib/libQt5Core.prl
	$(QMAKE) -o Makefile goodby.pro
../../../local/lib/qt5/mkspecs/features/spec_pre.prf:
../../../local/lib/qt5/mkspecs/common/unix.conf:
../../../local/lib/qt5/mkspecs/common/freebsd.conf:
../../../local/lib/qt5/mkspecs/common/sanitize.conf:
../../../local/lib/qt5/mkspecs/common/gcc-base.conf:
../../../local/lib/qt5/mkspecs/common/gcc-base-unix.conf:
../../../local/lib/qt5/mkspecs/common/clang.conf:
../../../local/lib/qt5/mkspecs/qconfig.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_core.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_dbus.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_gui.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_network.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_opengl.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_quick.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_webkit.pri:
../../../local/lib/qt5/mkspecs/modules/qt_config_widgets.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_core.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_declarative.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_help.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_network.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_script.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../local/lib/qt5/mkspecs/features/qt_functions.prf:
../../../local/lib/qt5/mkspecs/features/qt_config.prf:
../../../local/lib/qt5/mkspecs/freebsd-clang/qmake.conf:
../../../local/lib/qt5/mkspecs/features/spec_post.prf:
../../../local/lib/qt5/mkspecs/features/exclusive_builds.prf:
../../../local/lib/qt5/mkspecs/features/default_pre.prf:
../../../local/lib/qt5/mkspecs/features/resolve_config.prf:
../../../local/lib/qt5/mkspecs/features/default_post.prf:
../../../local/lib/qt5/mkspecs/features/warn_on.prf:
../../../local/lib/qt5/mkspecs/features/qt.prf:
../../../local/lib/qt5/mkspecs/features/resources.prf:
../../../local/lib/qt5/mkspecs/features/moc.prf:
../../../local/lib/qt5/mkspecs/features/unix/opengl.prf:
../../../local/lib/qt5/mkspecs/features/unix/thread.prf:
../../../local/lib/qt5/mkspecs/features/testcase_targets.prf:
../../../local/lib/qt5/mkspecs/features/exceptions.prf:
../../../local/lib/qt5/mkspecs/features/yacc.prf:
../../../local/lib/qt5/mkspecs/features/lex.prf:
goodby.pro:
/usr/local/lib/libQt5Gui.prl:
/usr/local/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile goodby.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents hello.c $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

hello.o: hello.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o hello.o hello.c

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

